# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FPGA/logtel/lab20_axi_3/bh_ddr_demo_wrapper.xdc

# Block Designs: bd/lab20_axi_3_bd/lab20_axi_3_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_axi_3_bd || ORIG_REF_NAME==lab20_axi_3_bd} -quiet] -quiet

# IP: bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_mig_7series_0_0/lab20_axi_3_bd_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_axi_3_bd_mig_7series_0_0 || ORIG_REF_NAME==lab20_axi_3_bd_mig_7series_0_0} -quiet] -quiet

# IP: bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_jtag_axi_0_0/lab20_axi_3_bd_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_axi_3_bd_jtag_axi_0_0 || ORIG_REF_NAME==lab20_axi_3_bd_jtag_axi_0_0} -quiet] -quiet

# IP: bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_axi_smc_0/lab20_axi_3_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_axi_3_bd_axi_smc_0 || ORIG_REF_NAME==lab20_axi_3_bd_axi_smc_0} -quiet] -quiet

# IP: bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_axi_3_bd_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab20_axi_3_bd_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/lab20_axi_3_bd_ooc.xdc
