@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 18 14:41:30 +0200 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim lab20_axi_3_bd_wrapper_behav -key {Behavioral:sim_1:Functional:lab20_axi_3_bd_wrapper} -tclbatch lab20_axi_3_bd_wrapper.tcl -protoinst "protoinst_files/bd_cc91.protoinst" -protoinst "protoinst_files/lab20_axi_3_bd.protoinst" -log simulate.log"
call xsim  lab20_axi_3_bd_wrapper_behav -key {Behavioral:sim_1:Functional:lab20_axi_3_bd_wrapper} -tclbatch lab20_axi_3_bd_wrapper.tcl -protoinst "protoinst_files/bd_cc91.protoinst" -protoinst "protoinst_files/lab20_axi_3_bd.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
