# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.srcs/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/lab22_axi_monitor_axi_smc_2.xci
# IP: The module: 'lab22_axi_monitor_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/bd_414f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_0/bd_414f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_2/bd_414f_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_3/bd_414f_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_4/bd_414f_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_5/bd_414f_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_6/bd_414f_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_7/bd_414f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_8/bd_414f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_9/bd_414f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_10/bd_414f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_11/bd_414f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_12/bd_414f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_13/bd_414f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_14/bd_414f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_15/bd_414f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_16/bd_414f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_17/bd_414f_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_18/bd_414f_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_19/bd_414f_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_20/bd_414f_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_21/bd_414f_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_22/bd_414f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_23/bd_414f_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_24/bd_414f_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_25/bd_414f_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_26/bd_414f_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_27/bd_414f_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_28/bd_414f_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_29/bd_414f_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_2/bd_414f_arsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_3/bd_414f_rsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_4/bd_414f_awsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_5/bd_414f_wsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_6/bd_414f_bsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_10/bd_414f_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_11/bd_414f_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_12/bd_414f_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_13/bd_414f_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_14/bd_414f_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_15/bd_414f_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_16/bd_414f_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_17/bd_414f_m00arn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_18/bd_414f_m00rn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_19/bd_414f_m00awn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_20/bd_414f_m00wn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_21/bd_414f_m00bn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_23/bd_414f_m01s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_24/bd_414f_m01arn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_25/bd_414f_m01rn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_26/bd_414f_m01awn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_27/bd_414f_m01wn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_28/bd_414f_m01bn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.srcs/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/lab22_axi_monitor_axi_smc_2.xci
# IP: The module: 'lab22_axi_monitor_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/bd_414f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_0/bd_414f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_2/bd_414f_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_3/bd_414f_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_4/bd_414f_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_5/bd_414f_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_6/bd_414f_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_7/bd_414f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_8/bd_414f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_9/bd_414f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_10/bd_414f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_11/bd_414f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_12/bd_414f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_13/bd_414f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_14/bd_414f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_15/bd_414f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_16/bd_414f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_17/bd_414f_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_18/bd_414f_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_19/bd_414f_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_20/bd_414f_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_21/bd_414f_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_22/bd_414f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_23/bd_414f_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_24/bd_414f_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_25/bd_414f_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_26/bd_414f_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_27/bd_414f_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_28/bd_414f_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_29/bd_414f_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_1/bd_414f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_2/bd_414f_arsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_3/bd_414f_rsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_4/bd_414f_awsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_5/bd_414f_wsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_6/bd_414f_bsw_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_10/bd_414f_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_11/bd_414f_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_12/bd_414f_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_13/bd_414f_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_14/bd_414f_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_15/bd_414f_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_16/bd_414f_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_17/bd_414f_m00arn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_18/bd_414f_m00rn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_19/bd_414f_m00awn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_20/bd_414f_m00wn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_21/bd_414f_m00bn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_23/bd_414f_m01s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_24/bd_414f_m01arn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_25/bd_414f_m01rn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_26/bd_414f_m01awn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_27/bd_414f_m01wn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/bd_0/ip/ip_28/bd_414f_m01bn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
