# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FPGA/logtel/lab20/bh_llb.xdc

# Block Designs: bd/lab20_block_design/lab20_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design || ORIG_REF_NAME==lab20_block_design} -quiet] -quiet

# IP: bd/lab20_block_design/ip/lab20_block_design_axi_uartlite_0_0/lab20_block_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design_axi_uartlite_0_0 || ORIG_REF_NAME==lab20_block_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/lab20_block_design_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design_jtag_axi_0_0 || ORIG_REF_NAME==lab20_block_design_jtag_axi_0_0} -quiet] -quiet

# IP: bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_imp_xbar_0/lab20_block_design_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==lab20_block_design_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_0/lab20_block_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design_axi_interconnect_0_0 || ORIG_REF_NAME==lab20_block_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/lab20_block_design/ip/lab20_block_design_clk_wiz_1/lab20_block_design_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_block_design_clk_wiz_1 || ORIG_REF_NAME==lab20_block_design_clk_wiz_1} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/lab20_block_design_ooc.xdc
