# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FPGA/logtel/for_axi_labs/bh_llb.xdc

# Block Designs: bd/lab20_2_bd/lab20_2_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd || ORIG_REF_NAME==lab20_2_bd} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_axi_uartlite_0_1/lab20_2_bd_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_axi_uartlite_0_1 || ORIG_REF_NAME==lab20_2_bd_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_jtag_axi_0_1/lab20_2_bd_jtag_axi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_jtag_axi_0_1 || ORIG_REF_NAME==lab20_2_bd_jtag_axi_0_1} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/lab20_2_bd_axi_smc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_axi_smc_3 || ORIG_REF_NAME==lab20_2_bd_axi_smc_3} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_clk_wiz_2/lab20_2_bd_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_clk_wiz_2 || ORIG_REF_NAME==lab20_2_bd_clk_wiz_2} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_rst_clk_wiz_100M_2 || ORIG_REF_NAME==lab20_2_bd_rst_clk_wiz_100M_2} -quiet] -quiet

# IP: bd/lab20_2_bd/ip/lab20_2_bd_reset_inv_0_0/lab20_2_bd_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab20_2_bd_reset_inv_0_0 || ORIG_REF_NAME==lab20_2_bd_reset_inv_0_0} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/lab20_2_bd_ooc.xdc
