# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xci
# IP: The module: 'char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xci
# IP: The module: 'char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/xilinx/training/Constr_Wizard/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/char_fifo/char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
