# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.srcs/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/design_lab19_axi_smc_0.xci
# IP: The module: 'design_lab19_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/bd_4998.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_0/bd_4998_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_2/bd_4998_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_3/bd_4998_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_4/bd_4998_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_5/bd_4998_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_6/bd_4998_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_7/bd_4998_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_8/bd_4998_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_9/bd_4998_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_10/bd_4998_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_11/bd_4998_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_12/bd_4998_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_5/bd_4998_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_6/bd_4998_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_7/bd_4998_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_8/bd_4998_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_9/bd_4998_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_10/bd_4998_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_11/bd_4998_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_lab19_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_lab19_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.srcs/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/design_lab19_axi_smc_0.xci
# IP: The module: 'design_lab19_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/bd_4998.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_0/bd_4998_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_2/bd_4998_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_3/bd_4998_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_4/bd_4998_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_5/bd_4998_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_6/bd_4998_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_7/bd_4998_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_8/bd_4998_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_9/bd_4998_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_10/bd_4998_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_11/bd_4998_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_12/bd_4998_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_1/bd_4998_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_5/bd_4998_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_6/bd_4998_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_7/bd_4998_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_8/bd_4998_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_9/bd_4998_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_10/bd_4998_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/bd_0/ip/ip_11/bd_4998_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_lab19_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/ip/design_lab19_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_lab19_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
