# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.srcs/BRAM_1/ip/BRAM_1/BRAM_1.xci
# IP: The module: 'BRAM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/BRAM_1/ip/BRAM_1/BRAM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.srcs/BRAM_1/ip/BRAM_1/BRAM_1.xci
# IP: The module: 'BRAM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/BRAM_1/ip/BRAM_1/BRAM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
