set_property SRC_FILE_INFO {cfile:C:/FPGA/logtel/lab19_axi/lab19_axi.srcs/constrs_1/new/constr_19.xdc rfile:../../../lab19_axi.srcs/constrs_1/new/constr_19.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports reset]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports reset_0]
