# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr_19.xdc

# Block Designs: bd/design_lab19/design_lab19.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19 || ORIG_REF_NAME==design_lab19} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_jtag_axi_0_0/design_lab19_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_jtag_axi_0_0 || ORIG_REF_NAME==design_lab19_jtag_axi_0_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_axi_bram_ctrl_0_0/design_lab19_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_lab19_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_axi_bram_ctrl_0_bram_0/design_lab19_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_lab19_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_axi_smc_0/design_lab19_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_axi_smc_0 || ORIG_REF_NAME==design_lab19_axi_smc_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_clk_wiz_0/design_lab19_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_clk_wiz_0 || ORIG_REF_NAME==design_lab19_clk_wiz_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_rst_clk_wiz_100M_0/design_lab19_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_lab19_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_lab19/ip/design_lab19_system_ila_0_0/design_lab19_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_lab19_system_ila_0_0 || ORIG_REF_NAME==design_lab19_system_ila_0_0} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab19_axi/lab19_axi.gen/sources_1/bd/design_lab19/design_lab19_ooc.xdc
