# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.srcs/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2.xci
# IP: The module: 'lab20_2_bd_rst_clk_wiz_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.srcs/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2.xci
# IP: The module: 'lab20_2_bd_rst_clk_wiz_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_rst_clk_wiz_100M_2/lab20_2_bd_rst_clk_wiz_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_rst_clk_wiz_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
