@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 12 21:45:13 +0200 2025
REM SW Build 5266912 on Sun Dec 15 09:03:24 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim design_for_ram_w_r_tb_behav -key {Behavioral:sim_1:Functional:design_for_ram_w_r_tb} -tclbatch design_for_ram_w_r_tb.tcl -view C:/FPGA/logtel/lab5_memories/rom_tb_behav.wcfg -view C:/FPGA/logtel/lab5_memories/ram_tb_behav.wcfg -view C:/FPGA/logtel/lab5_memories/design_for_rom_reading_tb_behav.wcfg -log simulate.log"
call xsim  design_for_ram_w_r_tb_behav -key {Behavioral:sim_1:Functional:design_for_ram_w_r_tb} -tclbatch design_for_ram_w_r_tb.tcl -view C:/FPGA/logtel/lab5_memories/rom_tb_behav.wcfg -view C:/FPGA/logtel/lab5_memories/ram_tb_behav.wcfg -view C:/FPGA/logtel/lab5_memories/design_for_rom_reading_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
