# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Work/Nexys-A7/Nexys-A7-HW/src/constraints/Nexys-A7-100T-Master.xdc

# IP: C:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: c:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr/user_design/constraints/ddr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr} -quiet] -quiet

# XDC: c:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc
