# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Work/Nexys-A7/Nexys-A7-HW/proj/Nexys-A7-HW.runs/synth_1/Nexys4DdrUserDemo.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Work/Nexys-A7/Nexys-A7-HW/proj/Nexys-A7-HW.cache/wt [current_project]
set_property parent.project_path C:/Work/Nexys-A7/Nexys-A7-HW/proj/Nexys-A7-HW.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Work/Nexys-A7/Nexys-A7-HW/repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Work/Nexys-A7/Nexys-A7-HW/proj/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Work/Nexys-A7/Nexys-A7-HW/src/other/Nexys4_all.coe
read_vhdl -library xil_defaultlib {
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/ADXL362Ctrl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/AccelArithmetics.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/AccelDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/AccelerometerCtl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/AudioDemo.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/Dbncr.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/FPGAMonitor.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/LedBar.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/LocalRst.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/LogoDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/SyncAsync.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/MicDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/MouseCtl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/MouseDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/OverlayCtl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/PdmDes.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/PdmSer.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/Ps2Interface.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/Pwm.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/Ram2Ddr.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/RamCntrl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/RgbLed.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/RgbLedDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/SPI_If.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/TWICtl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/TempDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/TempSensorCtl.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/Vga.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/sSegDemo.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/sSegDisplay.vhd
  C:/Work/Nexys-A7/Nexys-A7-HW/src/hdl/top.vhd
}
read_ip -quiet C:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr.xci
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr/user_design/constraints/ddr.xdc]
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc]

read_ip -quiet C:/Work/Nexys-A7/Nexys-A7-HW/src/ip/BRAM_1/BRAM_1.xci
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/proj/hw.gen/sources_1/ip/BRAM_1/BRAM_1_ooc.xdc]

read_ip -quiet C:/Work/Nexys-A7/Nexys-A7-HW/src/ip/ClkGen/ClkGen.xci
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_board.xdc]
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/proj/hw.gen/sources_1/ip/ClkGen/ClkGen.xdc]
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/proj/hw.gen/sources_1/ip/ClkGen/ClkGen_ooc.xdc]

read_ip -quiet C:/Work/Nexys-A7/Nexys-A7-HW/src/ip/Square_Root/Square_Root.xci
set_property used_in_implementation false [get_files -all c:/Work/Nexys-A7/Nexys-A7-HW/proj/hw.gen/sources_1/ip/Square_Root/Square_Root_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Work/Nexys-A7/Nexys-A7-HW/src/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Work/Nexys-A7/Nexys-A7-HW/src/constraints/Nexys-A7-100T-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Work/Nexys-A7/Nexys-A7-HW/proj/Nexys-A7-HW.srcs/utils_1/imports/synth_1/Nexys4DdrUserDemo.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Nexys4DdrUserDemo -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nexys4DdrUserDemo.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Nexys4DdrUserDemo_utilization_synth.rpt -pb Nexys4DdrUserDemo_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
