# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.srcs/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0.xci
# IP: The module: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.srcs/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0.xci
# IP: The module: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_3/lab20_axi_3.gen/sources_1/bd/lab20_axi_3_bd/ip/lab20_axi_3_bd_rst_mig_7series_0_81M_0/lab20_axi_3_bd_rst_mig_7series_0_81M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_axi_3_bd_rst_mig_7series_0_81M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
