# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab20/lab20.srcs/sources_1/bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_imp_xbar_0/lab20_block_design_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'lab20_block_design_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_imp_xbar_0/lab20_block_design_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA/logtel/lab20/lab20.srcs/sources_1/bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_imp_xbar_0/lab20_block_design_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'lab20_block_design_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_axi_interconnect_0_imp_xbar_0/lab20_block_design_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
