# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab22_axi_monitor/lab22_axi_monitor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor || ORIG_REF_NAME==lab22_axi_monitor} -quiet] -quiet

# IP: bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/lab22_axi_monitor_jtag_axi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor_jtag_axi_0_1 || ORIG_REF_NAME==lab22_axi_monitor_jtag_axi_0_1} -quiet] -quiet

# IP: bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_perf_mon_0_1/lab22_axi_monitor_axi_perf_mon_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor_axi_perf_mon_0_1 || ORIG_REF_NAME==lab22_axi_monitor_axi_perf_mon_0_1} -quiet] -quiet

# IP: bd/lab22_axi_monitor/ip/lab22_axi_monitor_mig_7series_0_3/lab22_axi_monitor_mig_7series_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor_mig_7series_0_3 || ORIG_REF_NAME==lab22_axi_monitor_mig_7series_0_3} -quiet] -quiet

# IP: bd/lab22_axi_monitor/ip/lab22_axi_monitor_rst_mig_7series_0_81M_0/lab22_axi_monitor_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab22_axi_monitor_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/lab22_axi_monitor/ip/lab22_axi_monitor_axi_smc_2/lab22_axi_monitor_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_monitor_axi_smc_2 || ORIG_REF_NAME==lab22_axi_monitor_axi_smc_2} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/lab22_axi_monitor_ooc.xdc
