# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.srcs/ClkGen/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.srcs/ClkGen/ip/ClkGen/ClkGen.xci
# IP: The module: 'ClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab23_timing/Nexys-A7-HW/Nexys-A7-HW.gen/ClkGen/ip/ClkGen/ClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
