# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.srcs/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/lab22_axi_monitor_jtag_axi_0_1.xci
# IP: The module: 'lab22_axi_monitor_jtag_axi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_jtag_axi_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/lab22_axi_monitor_jtag_axi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_jtag_axi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.srcs/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/lab22_axi_monitor_jtag_axi_0_1.xci
# IP: The module: 'lab22_axi_monitor_jtag_axi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_jtag_axi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22_axi_monitor/lab22_axi_monitor.gen/sources_1/bd/lab22_axi_monitor/ip/lab22_axi_monitor_jtag_axi_0_1/lab22_axi_monitor_jtag_axi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab22_axi_monitor_jtag_axi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
