# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.srcs/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/lab20_2_bd_axi_smc_3.xci
# IP: The module: 'lab20_2_bd_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/bd_fbbb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_0/bd_fbbb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_2/bd_fbbb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_3/bd_fbbb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_4/bd_fbbb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_5/bd_fbbb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_6/bd_fbbb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_7/bd_fbbb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_8/bd_fbbb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_9/bd_fbbb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_10/bd_fbbb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_11/bd_fbbb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_12/bd_fbbb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_5/bd_fbbb_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_6/bd_fbbb_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_7/bd_fbbb_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_8/bd_fbbb_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_9/bd_fbbb_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_10/bd_fbbb_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_11/bd_fbbb_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_axi_smc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.srcs/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/lab20_2_bd_axi_smc_3.xci
# IP: The module: 'lab20_2_bd_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/bd_fbbb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_0/bd_fbbb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_2/bd_fbbb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_3/bd_fbbb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_4/bd_fbbb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_5/bd_fbbb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_6/bd_fbbb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_7/bd_fbbb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_8/bd_fbbb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_9/bd_fbbb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_10/bd_fbbb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_11/bd_fbbb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_12/bd_fbbb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_1/bd_fbbb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_5/bd_fbbb_s00a2s_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_6/bd_fbbb_sarn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_7/bd_fbbb_srn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_8/bd_fbbb_sawn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_9/bd_fbbb_swn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_10/bd_fbbb_sbn_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/bd_0/ip/ip_11/bd_fbbb_m00s2a_0_ooc.xdc

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20_axi_2/lab20_axi_2.gen/sources_1/bd/lab20_2_bd/ip/lab20_2_bd_axi_smc_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_2_bd_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
