# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab22/lab22.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22 || ORIG_REF_NAME==lab22} -quiet] -quiet

# IP: bd/lab22/ip/lab22_axi_perf_mon_0_0/lab22_axi_perf_mon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_perf_mon_0_0 || ORIG_REF_NAME==lab22_axi_perf_mon_0_0} -quiet] -quiet

# IP: bd/lab22/ip/lab22_mig_7series_0_0/lab22_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_mig_7series_0_0 || ORIG_REF_NAME==lab22_mig_7series_0_0} -quiet] -quiet

# IP: bd/lab22/ip/lab22_jtag_axi_0_0/lab22_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_jtag_axi_0_0 || ORIG_REF_NAME==lab22_jtag_axi_0_0} -quiet] -quiet

# IP: bd/lab22/ip/lab22_rst_mig_7series_0_81M_0/lab22_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab22_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/lab22/ip/lab22_axi_smc_0/lab22_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab22_axi_smc_0 || ORIG_REF_NAME==lab22_axi_smc_0} -quiet] -quiet

# XDC: c:/FPGA/logtel/lab22/lab22.gen/sources_1/bd/lab22/lab22_ooc.xdc
