# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/logtel/lab20/lab20.srcs/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/lab20_block_design_jtag_axi_0_0.xci
# IP: The module: 'lab20_block_design_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/lab20_block_design_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/logtel/lab20/lab20.srcs/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/lab20_block_design_jtag_axi_0_0.xci
# IP: The module: 'lab20_block_design_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/logtel/lab20/lab20.gen/sources_1/bd/lab20_block_design/ip/lab20_block_design_jtag_axi_0_0/lab20_block_design_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab20_block_design_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
