# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Nexys4DDR_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_devider_0_0/design_1_clock_devider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_devider_0_0 || ORIG_REF_NAME==design_1_clock_devider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vga_top_0_0/design_1_vga_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_top_0_0 || ORIG_REF_NAME==design_1_vga_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7670_controller_0_0/design_1_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ov7670_controller_0_0 || ORIG_REF_NAME==design_1_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ovo_7670_caputre_0_0/design_1_ovo_7670_caputre_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ovo_7670_caputre_0_0 || ORIG_REF_NAME==design_1_ovo_7670_caputre_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
